-- GLOBALMUSIC DATABASE
-- =========================================

create extension if not exists pg_trgm;


-- =========================================
-- UPDATED AT FONKSİYONU
-- =========================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- =========================================
-- SANATÇILAR
-- =========================================

create table if not exists public.artists (
  id bigint generated by default as identity primary key,

  name text not null,
  normalized_name text unique,

  image_url text,
  country text,
  biography text,

  genres text[],

  external_ids jsonb default '{}'::jsonb,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- =========================================
-- ALBÜMLER
-- =========================================

create table if not exists public.albums (
  id bigint generated by default as identity primary key,

  artist_id bigint
    references public.artists(id)
    on delete set null,

  title text not null,
  normalized_title text,

  cover_url text,
  release_date date,

  album_type text,
  genres text[],

  external_ids jsonb default '{}'::jsonb,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- =========================================
-- ŞARKILAR
-- =========================================

create table if not exists public.tracks (
  id bigint generated by default as identity primary key,

  artist_id bigint
    references public.artists(id)
    on delete set null,

  album_id bigint
    references public.albums(id)
    on delete set null,

  title text not null,
  normalized_title text,

  duration_seconds integer,

  track_number integer,
  disc_number integer,

  language text,
  genre text,

  release_date date,

  cover_url text,

  preview_url text,
  stream_url text,

  source_name text,
  source_url text,

  external_ids jsonb default '{}'::jsonb,

  downloadable boolean default false,
  download_url text,

  is_explicit boolean default false,
  is_active boolean default true,

  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  unique(source_name, source_url)
);


-- =========================================
-- VİDEOLAR
-- =========================================

create table if not exists public.videos (
  id bigint generated by default as identity primary key,

  artist_id bigint
    references public.artists(id)
    on delete set null,

  title text not null,
  normalized_title text,

  description text,

  thumbnail_url text,

  duration_seconds integer,

  source_name text,
  source_url text,

  video_url text,

  quality text,

  downloadable boolean default false,
  download_url text,

  language text,
  genre text,

  published_at timestamptz,

  external_ids jsonb default '{}'::jsonb,

  is_active boolean default true,

  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  unique(source_name, source_url)
);


-- =========================================
-- KAYNAKLAR
-- =========================================

create table if not exists public.sources (
  id bigint generated by default as identity primary key,

  name text not null unique,

  source_type text,
  base_url text,

  enabled boolean default true,

  last_scan_at timestamptz,
  last_success_at timestamptz,

  total_items_found bigint default 0,
  total_items_added bigint default 0,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- =========================================
-- OTOMATİK TARAMALAR
-- =========================================

create table if not exists public.scan_runs (
  id bigint generated by default as identity primary key,

  source_id bigint
    references public.sources(id)
    on delete set null,

  started_at timestamptz default now(),
  finished_at timestamptz,

  status text default 'running',

  items_found bigint default 0,
  items_added bigint default 0,
  items_updated bigint default 0,
  items_skipped bigint default 0,

  error_message text
);


-- =========================================
-- ARAMA İNDEKSLERİ
-- =========================================

create index if not exists idx_artists_name
on public.artists
using gin (name gin_trgm_ops);


create index if not exists idx_tracks_title
on public.tracks
using gin (title gin_trgm_ops);


create index if not exists idx_tracks_created
on public.tracks(created_at desc);


create index if not exists idx_videos_title
on public.videos
using gin (title gin_trgm_ops);


create index if not exists idx_videos_created
on public.videos(created_at desc);


-- =========================================
-- TEMEL KAYNAKLAR
-- =========================================

insert into public.sources
(
  name,
  source_type,
  enabled
)
values
(
  'Global Music Sources',
  'music_metadata',
  true
),
(
  'Global Video Sources',
  'video_metadata',
  true
)
on conflict (name) do nothing;


-- =========================================
-- RLS
-- =========================================

alter table public.artists enable row level security;

alter table public.albums enable row level security;

alter table public.tracks enable row level security;

alter table public.videos enable row level security;


-- =========================================
-- SANATÇI OKUMA
-- =========================================

drop policy if exists "Public artists"
on public.artists;

create policy "Public artists"
on public.artists
for select
to anon, authenticated
using (true);


-- =========================================
-- ALBÜM OKUMA
-- =========================================

drop policy if exists "Public albums"
on public.albums;

create policy "Public albums"
on public.albums
for select
to anon, authenticated
using (true);


-- =========================================
-- ŞARKI OKUMA
-- =========================================

drop policy if exists "Public active tracks"
on public.tracks;

create policy "Public active tracks"
on public.tracks
for select
to anon, authenticated
using (is_active = true);


-- =========================================
-- VİDEO OKUMA
-- =========================================

drop policy if exists "Public active videos"
on public.videos;

create policy "Public active videos"
on public.videos
for select
to anon, authenticated
using (is_active = true);
